apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-ludic-bot
  labels:
    app: telegram-ludic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-ludic-bot
  template:
    metadata:
      labels:
        app: telegram-ludic-bot
    spec:
      # --- ОБХОД DNS ---
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "8.8.8.8"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      # ------------------
      
      containers:
      - name: telegram-ludic-bot
        # !!! ВАЖНО: ЗАМЕНИТЕ ЭТУ СТРОКУ НА ВАШ РЕАЛЬНЫЙ ОБРАЗ Docker
        # Пример: gmo433/ludic-bot:latest
        image: <ВАШ_DOCKER_IMAGE_ЗДЕСЬ>  
        ports:
        - containerPort: 8080
        
        env:
        # 1. Секрет для токена Telegram
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secret
              key: token
              
        # 2. Секрет для API-Sport.ru
        - name: API_SPORT_KEY
          valueFrom:
            secretKeyRef:
              name: api-sport-secret
              key: API_SPORT_KEY
