apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-ludic-bot
  labels:
    app: telegram-ludic-bot
spec:
  replicas: 2 # 2 реплики для отказоустойчивости
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: telegram-ludic-bot
  template:
    metadata:
      labels:
        app: telegram-ludic-bot
    spec:
      # --- ОБХОД DNS ---
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "8.8.8.8"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      # -----------------
      containers:
      - name: hello-bot
        image: docker.io/roman3327/ludic-bot:latest 
        imagePullPolicy: Always
        env:
        # 1. Telegram Token
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secret
              key: token
        # 2. Football API Key
        - name: API_FOOTBALL_KEY
          valueFrom:
            secretKeyRef:
              name: football-api-secret
              key: key
        # --- ПРОБЫ ЖИЗНЕСПОСОБНОСТИ ---
        livenessProbe:
          exec:
            command: ["/bin/true"]
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["/bin/true"]
          initialDelaySeconds: 10
          periodSeconds: 10
        # --------------------------------
        resources:
          limits:
            memory: "512Mi"
            cpu: "800m"
          requests:
            memory: "256Mi"
            cpu: "400m"
---
apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
type: Opaque
---
# Новый Secret для ключа API Football
apiVersion: v1
kind: Secret
metadata:
  name: football-api-secret
type: Opaque
