apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-ludic-bot
  labels:
    app: telegram-ludic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-ludic-bot
  template:
    metadata:
      labels:
        app: telegram-ludic-bot
    spec:
      # --- ОБХОД DNS (Для исправления ошибок Could not resolve host) ---
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "8.8.8.8"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      # ------------------------------------------------------------------
      
      containers:
      - name: telegram-ludic-bot
        image: <ВАШ_DOCKER_IMAGE_ЗДЕСЬ>  # !!! ВСТАВЬТЕ СВОЙ ОБРАЗ Docker. Например: gmo433/ludic-bot:latest
        ports:
        - containerPort: 8080
        
        env:
        # 1. Секрет для токена Telegram
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secret
              key: token
              
        # 2. НОВЫЙ Секрет для API-Sport.ru
        - name: API_SPORT_KEY  # <-- Новая переменная, используемая в main.go
          valueFrom:
            secretKeyRef:
              name: api-sport-secret # <-- Имя Secret, который вы создали
              key: API_SPORT_KEY    # <-- Имя ключа внутри Secret
