apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-ludic-bot
  labels:
    app: telegram-ludic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-ludic-bot
  template:
    metadata:
      labels:
        app: telegram-ludic-bot
    spec:
      # !!! КРИТИЧЕСКОЕ ИСПРАВЛЕНИЕ: ПРИНУДИТЕЛЬНЫЙ ВНЕШНИЙ DNS !!!
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "8.8.8.8"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      # ------------------------------------------------------------------
      containers:
      - name: hello-bot
        # !!! ПЛЕЙСХОЛДЕР: Замените <ВАШ_DOCKER_USERNAME> !!!
        image: docker.io/<ВАШ_DOCKER_USERNAME>/ludic-bot:latest 
        imagePullPolicy: Always
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secret
              key: token
        resources:
          limits:
            memory: "512Mi"
            cpu: "800m"
          requests:
            memory: "256Mi"
            cpu: "400m"
---
# Secret должен быть создан пайплайном
apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
type: Opaque
