apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-ludic-bot
  labels:
    app: telegram-ludic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-ludic-bot
  template:
    metadata:
      labels:
        app: telegram-ludic-bot
    spec:
      containers:
      - name: hello-bot
        # !!! ВАЖНО: ЗАМЕНИТЕ <ВАШ_DOCKER_USERNAME> НА СВОЙ ЛОГИН !!!
        image: docker.io/<ВАШ_DOCKER_USERNAME>/ludic-bot:latest 
        imagePullPolicy: Always
        # Получаем токен из Kubernetes Secret
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secret
              key: token
        # =========================================================
        # НОВЫЕ ПАРАМЕТРЫ РЕСУРСОВ (Увеличены в 8 раз)
        resources:
          limits:
            memory: "512Mi" # Было 64Mi * 8
            cpu: "800m"     # Было 100m * 8 (т.е. 0.8 CPU)
          requests:
            memory: "256Mi" # Было 32Mi * 8
            cpu: "400m"     # Было 50m * 8 (т.е. 0.4 CPU)
        # =========================================================
---
# Этот Secret будет создан/обновлен пайплайном GitHub Actions
apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secret
type: Opaque
