apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-ludic-bot
  labels:
    app: telegram-ludic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-ludic-bot
  template:
    metadata:
      labels:
        app: telegram-ludic-bot
    spec:
      # --- ОБХОД DNS (Устраняет ошибку "Could not resolve host") ---
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "8.8.8.8"
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      # ------------------------------------------------------------------
      
      containers:
      - name: telegram-ludic-bot
        # ИСПРАВЛЕНИЕ: ТОЧНОЕ ИМЯ ВАШЕГО ОБРАЗА С DOCKER HUB
        image: roman3327/ludic-bot:latest  
        ports:
        - containerPort: 8080
        
        env:
        # 1. Секрет для токена Telegram
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: telegram-bot-secret
              key: token
              
        # 2. Секрет для API-Sport.ru (Устраняет ошибку 451)
        - name: API_SPORT_KEY
          valueFrom:
            secretKeyRef:
              name: api-sport-secret
              key: API_SPORT_KEY
