apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets 
type: Opaque
data:
  # ЗАМЕНИТЕ ЭТИ ЗАГЛУШКИ НА ВАШИ base64-ЗНАЧЕНИЯ!
  TELEGRAM_BOT_TOKEN: PLACEHOLDER_TELEGRAM_BOT_TOKEN_BASE64 
  API_SPORT_KEY: PLACEHOLDER_API_SPORT_KEY_BASE64
