apiVersion: apps/v1
kind: Deployment
metadata:
  name: ludic-bot
  labels:
    app: ludic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ludic-bot
  template:
    metadata:
      labels:
        app: ludic-bot
    spec:
      containers:
      - name: ludic-bot
        image: ghcr.io/YOUR_GITHUB_USERNAME/ludic-bot:latest
        imagePullPolicy: Always
        env:
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: ludic-bot-secrets
              key: TELEGRAM_TOKEN
        - name: API_FOOTBALL_KEY
          valueFrom:
            secretKeyRef:
              name: ludic-bot-secrets
              key: API_FOOTBALL_KEY
        - name: API_FOOTBALL_HOST
          value: "v3.football.api-sports.io"
