apiVersion: apps/v1
kind: Deployment
metadata:
  name: ludic-bot
  labels:
    app: ludic-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ludic-bot
  template:
    metadata:
      labels:
        app: ludic-bot
    spec:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - default.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "2"
          - name: timeout
            value: "2"
          - name: attempts
            value: "3"
      containers:
        - name: ludic-bot
          image: roman3327/ludic-bot:latest
          ports:
            - containerPort: 8080
          env:
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: TELEGRAM_BOT_TOKEN
            - name: API_SPORT_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: API_SPORT_KEY
            - name: WEBAPP_URL
              value: ""  # optional: set to your public URL if available
