apiVersion: v1
kind: Secret
metadata:
  name: ludic-bot-secrets
type: Opaque
stringData:
  TELEGRAM_TOKEN: "REPLACE_WITH_YOUR_TELEGRAM_TOKEN"
  API_FOOTBALL_KEY: "REPLACE_WITH_YOUR_API_KEY"
  API_FOOTBALL_HOST: "v3.football.api-sports.io"
