apiVersion: v1
kind: Secret
metadata:
  name: football-bot-secrets
type: Opaque
stringData:
  # Ключи, которые ищет Go-приложение
  TELEGRAM_BOT_TOKEN: "ВАШ_ТОКЕН_ИЗ_TELEGRAM_TOKEN_SECRET" # Go-код ищет TELEGRAM_BOT_TOKEN
  API_FOOTBALL_KEY: "ВАШ_КЛЮЧ_ИЗ_API_FOOTBALL_KEY_SECRET"
