deploy:
  name: Deploy to Kubernetes
  runs-on: ubuntu-latest
  needs: build-and-push
  
  # Определяем env-переменные для всего Job
  env:
    REGISTRY: docker.io
    IMAGE_NAME: ludic-bot

  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    # КРИТИЧЕСКОЕ ИСПРАВЛЕНИЕ: Преобразуем имя пользователя Docker Hub в нижний регистр 
    - name: Set Lowercase Docker Username
      id: set_user_lower
      run: |
        # Используем bash для приведения имени пользователя к нижнему регистру
        LOWER_USER=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
        echo "DOCKERHUB_USER_LOWER=$LOWER_USER" >> $GITHUB_ENV
        
    # Установим утилиту envsubst, необходимую для безопасной подстановки секретов
    - name: Install Gettext (for envsubst)
      run: sudo apt-get update && sudo apt-get install -y gettext-base

    # 1. Настройка Kubeconfig (для аутентификации в вашем кластере)
    - name: Set up Kubeconfig
      run: |
        # Декодируем base64 KUBECONFIG из секрета
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > /tmp/kubeconfig
        echo "KUBECONFIG=/tmp/kubeconfig" >> $GITHUB_ENV # Устанавливаем переменную окружения
        
    # 2. Установка kubectl
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3

    # 3. Применение манифестов с безопасной подстановкой секретов и имени образа
    - name: Apply Kubernetes Manifests
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
        
        # IMAGE_PATH использует НОВУЮ переменную, гарантированно строчную
        IMAGE_PATH: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_USER_LOWER }}/${{ env.IMAGE_NAME }}:latest
      run: |
        echo "Starting K8s deployment..."

        # 1. Подставляем секреты в secret.yaml
        envsubst < kubernetes/secret.yaml | kubectl apply -f -
        
        # 2. Подставляем путь к образу в deployment.yaml и применяем его
        envsubst '$IMAGE_PATH' < kubernetes/deployment.yaml | kubectl apply -f -
        
        # Ожидаем завершения деплоя
        kubectl rollout status deployment/football-bot-deployment --timeout=5m
        echo "Deployment successful! Bot is running in Kubernetes."
