name: 🚀 Build & Deploy Ludic Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy to Kubernetes
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: roman3327/ludic-bot
      KUBE_CONFIG_PATH: /tmp/kubeconfig

    steps:
      # 1️⃣ Проверяем код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Логинимся в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3️⃣ Собираем Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      # 4️⃣ Пушим в Docker Hub
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

      # 5️⃣ Настраиваем kubectl
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 --decode > $KUBE_CONFIG_PATH

      # 6️⃣ Деплоим в Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig=$KUBE_CONFIG_PATH apply -f k8s/

      # 7️⃣ Проверяем статус подов
      - name: Verify Deployment
        run: |
          kubectl --kubeconfig=$KUBE_CONFIG_PATH get pods -o wide
