name: Build and Deploy Ludic Bot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    # Генерация go.sum
    - name: Generate go.sum
      run: |
        go mod tidy
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add go.sum
        git commit -m "Auto-generate go.sum" || echo "No changes to commit"
        git push || echo "Push skipped"

    # Кешируем зависимости Go
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/go/cache
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # Сборка Docker образа
    - name: Build Docker image
      run: |
        docker build -t ludic-bot:latest .
        docker tag ludic-bot:latest ${{ secrets.DOCKERHUB_USERNAME }}/ludic-bot:latest

    # Логин в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Пуш Docker образа
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ludic-bot:latest

    # Настройка kubectl
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG_B64 }}" > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    # Деплой PostgreSQL
    - name: Deploy PostgreSQL
      run: kubectl apply -f k8s/postgres-deployment.yaml

    # Деплой Secrets
    - name: Deploy Secrets
      run: kubectl apply -f k8s/ludic-bot-secrets.yaml

    # Деплой Ludic Bot
    - name: Deploy Ludic Bot
      run: |
        sed -i "s|<dockerhub-username>|${{ secrets.DOCKERHUB_USERNAME }}|g" k8s/ludic-bot-deployment.yaml
        kubectl apply -f k8s/ludic-bot-deployment.yaml
