name: Deploy Ludic Bot to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.2

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/ludic-bot:latest
        build-args: |
          API_FOOTBALL_KEY=${{ secrets.API_FOOTBALL_KEY }}
          TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}

    - name: Set kubeconfig from base64
      run: |
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

    - name: Test kubectl connection
      run: kubectl get nodes

    - name: Deploy PostgreSQL
      run: kubectl apply -f k8s/postgres-deployment.yaml --validate=false

    - name: Deploy Ludic Bot (5 replicas)
      run: kubectl apply -f k8s/ludic-bot-deployment.yaml --validate=false
